---
- name: laba 5
  hosts: all
  become: yes
  vars:
    nginx_listen_port: 8080
  tasks:
    
    - name: blocks web
      block:    #======settings for webservers
        - name: Install EPEL Repo package from standard repo
          yum:
            name:
              - epel-release
              - nginx
            state: latest
        - name: Create config file from template
          template:
            src: nginx_port.conf.j2
            dest: /etc/nginx/nginx.conf
          notify:
            - reload nginx
        - name: show index htm
          template:
            src: index.html.j2
            dest: /usr/share/nginx/html/index.html
          notify:
            - reload nginx
      when: inventory_hostname in groups['web']

    - name: setting proxy
      block:
        - name: Install EPEL Repo, keepalived, haproxy
          yum:
            name:
              - epel-release
              - keepalived
              - haproxy
            state: latest
        - name: nukleus
          sysctl:
            name: net.ipv4.ip_nonlocal_bind
            value: '1'
            state: present
        - name: config keepalived
          template:
            src: keepalived.conf.j2
            dest: /etc/keepalived/keepalived.conf
          notify:
            - Restart keepalived
        - name: config haproxy
          template:
            src: haproxy.cfg.j2
            dest: /etc/haproxy/haproxy.cfg
          notify:
            - Restart HAProxy
        - name: stop firewalld
          systemd:
            name: firewalld
            state: stopped
            enabled: no  
      when: inventory_hostname in groups['server']

  handlers:
    - name: reload nginx
      systemd:
        name: nginx
        state: restarted
        # enabled: yes
    - name: reload file
      systemd:
        name: nginx
        state: restarted
    - name: Restart HAProxy
      service:
        name: haproxy
        state: restarted
    - name: Restart keepalived
      service:
        name: keepalived
        state: restarted